Add CallToAction screen
lana/b2c-mapp-ui pull request #89
Opened 2020-09-21 14:17 UTC by TanMar23

## Description
This PR is intended to resolve https://app.clubhouse.io/lanahub/story/4002/calltoactionscreen-implementation-in-the-ui-library

"We saw many times this screen repeated across different repos. This screen is just about a title + description + image + button, so it would be nice to make it generic and configurable to avoid code to be repeated each time we have to implement a screen similar than this one."

## Testing
- npm run lint: **PASS**
- npm run test: **PASS**
- Tested using Storybook

## Screenshots/Captures
![CallToActionScreen](https://user-images.githubusercontent.com/53623817/93778032-1071c800-fbeb-11ea-9d33-29e9d12ef421.png)

## Checks
- [ ] Requires documentation update
- [x] Requires lib version update

## Versioning impact
- [ ] **MAJOR** incompatible API changes.
- [ ] **MINOR** adds functionality in a backwards-compatible manner.
- [x] **PATCH** backwards-compatible bug fixes.

2020-09-21 14:21 UTC, jasonadt commented on src/components/CallToActionScreen/CallToActionScreen.js
> +  ButtonText: {
(camelCase) please rename this prop with standard camelCase to: `buttonText`

2020-09-21 14:22 UTC, jasonadt commented on src/components/CallToActionScreen/CallToActionScreen.stories.js
> +    ButtonText: {
Same here, should be: `buttonText`

2020-09-21 14:22 UTC, jasonadt commented on src/components/CallToActionScreen/CallToActionScreen.stories.js
> +                          :ButtonText="ButtonText"
Please always use `kebab-case` for markup props. Should be: 

```js
:button-text="buttonText"
```

2020-09-21 14:22 UTC, jantocv commented on src/components/CallToActionScreen/CallToActionScreen.js
> +  ButtonText: {
Lowercase first ;) 

```suggestion
  buttonText: {
```

2020-09-21 14:23 UTC, jasonadt commented on src/components/CallToActionScreen/CallToActionScreen.vue
> +      <WrappedButton :data-testid="dataTestId" @click="onClick"> {{ ButtonText }} </WrappedButton>
Should be: `buttonText`

2020-09-21 14:24 UTC, jasonadt requested changes
Nice work! Just a few small changes before I'll approve.

2020-09-21 14:26 UTC, jantocv requested changes
Good job!!! 🚀  Please check my suggestions, specially the `ScrollScreen` one, because it will help to have a scrollable content in the `slot` part and not to hide the Button when we scroll it.

2020-09-21 14:26 UTC, jantocv commented on src/components/CallToActionScreen/CallToActionScreen.vue
> +    </Wrapper>
Adding a ScrollWrapper here:

```suggestion
<ScrollWrapper>
    <Wrapper modal>
      <Heading class="title">{{ title }}</Heading>
      <TextParagraph> {{ description }}</TextParagraph>
    </Wrapper>
    <Wrapper>
      <slot/>
    </Wrapper>
</ScrollWrapper>
```

You can remove the `<div class="button-container">` and let the `<WrappedButton>` to be alone ;)

2020-09-21 14:26 UTC, jantocv commented on src/components/CallToActionScreen/CallToActionScreen.scss
> +}
If you add the `<ScrollScreen>` you will not need this ;)

2020-09-22 08:41 UTC, jasonadt submitted a review, later dismissed
👍  great work! 🎉

2020-09-22 10:28 UTC, jantocv approved these changes
I was waiting for this PR :) well done 🚀 
![](https://media.giphy.com/media/tctTjuqHP2Wk0/giphy.gif)

2020-09-22 10:54 UTC, jasonadt approved these changes
👍  🎉  ship it!

2020-09-22 10:55 UTC, merged